version: "3"

services:
  gitea:
    image: gitea/gitea:1.21.0
    container_name: gitea
    environment:
      - USER_UID=1002
      - USER_GID=100
    restart: always
    volumes:
      - ./gitea:/data
      - /home/git/.ssh/:/data/git/.ssh
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "2222:22"
    networks:
      - caddy

  soft-serve:
    container_name: soft-serve
    image: charmcli/soft-serve:v0.6.2
    restart: unless-stopped
    volumes:
      - ./soft/data:/soft-serve
    ports:
      - 23231:23231
      - 23232:23232
      - 23233:23233
      - 9418:9418

networks:
  caddy:
    external: true

