version: "3"

services:
  gitea:
    image: gitea/gitea:1.18.3
    container_name: gitea
    environment:
      - USER_UID=1002
      - USER_GID=100
    restart: always
    volumes:
      - ./gitea:/data
      - /home/git/.ssh/:/data/git/.ssh
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "127.0.0.1:3000:3000"
      - "127.0.0.0:222:22"
      - "127.0.0.1:2222:22"

  caddy:
    image: caddy:2.5.2-alpine
    restart: unless-stopped
    container_name: caddy
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    network_mode: host

  soft-serve:
    image: charmcli/soft-serve:v0.4.4
    restart: unless-stopped
    container_name: soft-serve
    volumes:
      - ./soft/data:/soft-serve
    ports:
      - 23231:23231

volumes:
  caddy_data:
    external: true
  caddy_config:
