services:
  forgejo:
    image: codeberg.org/forgejo/forgejo:10.0.1
    container_name: forgejo
    environment:
      # git user
      - USER_UID=1001
      - USER_GID=100
    restart: always
    volumes:
      - ./forgejo:/data
      - /home/git/.ssh/:/data/git/.ssh
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "3000:3000"
      - "2222:22"

  soft-serve:
    container_name: soft-serve
    # v0.8.2 broke mirroring
    image: charmcli/soft-serve:v0.8.1
    restart: unless-stopped
    volumes:
      - ./soft/data:/soft-serve
    ports:
      - 23231:23231
      - 23232:23232
      - 23233:23233
      - 9418:9418

